# Generated by Django 3.2.6 on 2021-08-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('head_1', models.CharField(max_length=70, verbose_name='Заголовок 1')),
                ('text_1', models.TextField(verbose_name='Текст для 1-го заголовка')),
                ('head_2', models.CharField(max_length=70, verbose_name='Заголовок 2')),
                ('text_2', models.TextField(verbose_name='Текст для 2-го заголовка')),
                ('head_3', models.CharField(max_length=70, verbose_name='Заголовок 3')),
                ('text_3', models.TextField(verbose_name='Текст для 1-го заголовка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='ClassForMainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Класс для галереи',
                'verbose_name_plural': 'Классы для галереи',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider/', verbose_name='Изображение')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('url', models.URLField(default='#', verbose_name='Ссылка')),
                ('button_name', models.CharField(max_length=30, verbose_name='Название кнопки')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('class_obj', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mainapp.classformaingallery', verbose_name='Класс для галереи')),
                ('image', models.ImageField(blank=True, upload_to='images/home-page/projects', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_desc', models.CharField(blank=True, max_length=50, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
