# Generated by Django 3.2.6 on 2021-08-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classformaingallery',
            options={'verbose_name': 'Класс для галереи', 'verbose_name_plural': 'Классы для галереи'},
        ),
        migrations.AlterModelOptions(
            name='maingallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='classformaingallery',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='class_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mainapp.classformaingallery', verbose_name='Класс для галереи'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='home-page/projects', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='short_desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание'),
        ),
    ]
