# Generated by Django 3.2.6 on 2021-08-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210812_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/2', verbose_name='Изображение')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('url', models.URLField(default='#', verbose_name='Ссылка')),
                ('button_name', models.CharField(max_length=30, verbose_name='Название кнопки')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
