# Generated by Django 3.2.6 on 2021-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_mainslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maingallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/home-page/projects', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(upload_to='images/slider/', verbose_name='Изображение'),
        ),
    ]
