# Generated by Django 3.2.6 on 2021-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210818_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('head_1', models.CharField(max_length=70, verbose_name='Заголовок 1')),
                ('text_1', models.TextField(verbose_name='Текст для 1-го заголовка')),
                ('head_2', models.CharField(max_length=70, verbose_name='Заголовок 2')),
                ('text_2', models.TextField(verbose_name='Текст для 2-го заголовка')),
                ('head_3', models.CharField(max_length=70, verbose_name='Заголовок 3')),
                ('text_3', models.TextField(verbose_name='Текст для 1-го заголовка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
